version: '3.8'

services:
  mongodb-booking-service:
    image: docker.io/bitnami/mongodb:5.0  
    environment:
      - MONGODB_ROOT_PASSWORD=password123  
    volumes:
      - 'mongodb-booking-service_data:/bitnami/mongodb'  
    ports:
      - '27017:27017'  

  mongodb-offers-service:
    image: docker.io/bitnami/mongodb:5.0  
    environment:
      - MONGODB_ROOT_PASSWORD=password123
    volumes:
      - 'mongodb-offers-service_data:/bitnami/mongodb'  
    ports:
      - '27018:27017'  

  admin-service-1:
    image: postgres:14
    environment:
      POSTGRES_DB: admin-service
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    volumes:
      - 'admin-service-1_data:/var/lib/postgresql/data'
    ports:
      - '5632:5432'

  user-service-2:
    image: postgres:14
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    volumes:
      - 'user-service-2_data:/var/lib/postgresql/data'
    ports:
      - '5633:5432'

  auth-service-3:
    image: postgres:14
    environment:
      POSTGRES_DB: auth-service
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
    volumes:
      - 'auth-service-3_data:/var/lib/postgresql/data'
    ports:
      - '5634:5432'

  payments-service-5:
    image: postgres:14
    environment:
      POSTGRES_DB: payments-service
      POSTGRES_USER: user5
      POSTGRES_PASSWORD: password5
    volumes:
      - 'payments-service-5_data:/var/lib/postgresql/data'
    ports:
      - '5639:5432'

volumes:
  mongodb-booking-service_data:
    driver: local  
  mongodb-offers-service_data:
    driver: local  
  admin-service-1_data:
    driver: local
  user-service-2_data:
    driver: local
  auth-service-3_data:
    driver: local
  payments-service-5_data:
    driver: local
